version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
      - VITE_USE_MOCK_DATA=false
    depends_on:
      - backend
    networks:
      - cinefluent-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - SECRET_KEY=your-secret-key-change-in-production
      - DEBUG=True
      - ENVIRONMENT=development
      - BACKEND_CORS_ORIGINS=["http://localhost:3000","http://localhost:8080","http://localhost:5173"]
    networks:
      - cinefluent-network

networks:
  cinefluent-network:
    driver: bridge