version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - cinefluent-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/cinefluent
    depends_on:
      - db
      - redis
    networks:
      - cinefluent-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=cinefluent
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - cinefluent-network

  redis:
    image: redis:7-alpine
    networks:
      - cinefluent-network

volumes:
  postgres_data:

networks:
  cinefluent-network:
    driver: bridge
